config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  get 'bemvindo' => 'home#index'

  resources :telefones # Gera 8 rotas de forma automática para este recurso
  resources :enderecos # Gera 8 rotas de forma automática para este recurso
  resources :contatos #, only: [:edit] 
  resources :tipos #, except: [:edit] 
  

end

app/models/contato.rb
class Contato < ActiveRecord::Base
  belongs_to :tipo
  has_one :endereco
  has_many :telefones
  
  validates :nome, presence: true, length: {minimum: 3}
  validates :email, presence: true
  
  accepts_nested_attributes_for :telefones, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :endereco
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
  belongs_to :contato
end

app/models/telefone.rb
class Telefone < ActiveRecord::Base
  belongs_to :contato
end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
  has_many :contatos
  validates :descricao, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  http_basic_authenticate_with name: "icaro", password: "admin", only: :destroy
  
  before_action :set_contato, only: [:show, :edit, :update, :destroy]
  before_action :set_opcoes_para_o_select, only: [:edit, :create, :new, :update]

  # GET /contatos
  # GET /contatos.json
  def index
    @contatos = Contato.all.order(:nome).page(params[:page]).per(15)
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
    @contato.build_endereco
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to contatos_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to contatos_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_path, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
  
    def set_opcoes_para_o_select  
      @opcoes_tipos_para_select = Tipo.all
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:nome, :email, :tipo_id, :observacao, 
        endereco_attributes: [:rua, :cidade, :estado],
        telefones_attributes: [:id, :telefone, :_destroy])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @nome_adm = "Ícaro Falcão"
  end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  http_basic_authenticate_with name: "icaro", password: "admin", only: :destroy
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]

  # GET /tipos
  # GET /tipos.json
  def index
    @tipos = Tipo.all
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
  end

  # POST /tipos
  # POST /tipos.json
  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to tipos_path, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos/1
  # PATCH/PUT /tipos/1.json
  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to tipos_path, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_path, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_params
      params.require(:tipo).permit(:descricao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ESTADOS_BRASILEIROS = [
    ["Acre", "AC"],
    ["Alagoas", "AL"],
    ["Amapá", "AP"],
    ["Amazonas", "AM"],
    ["Bahia", "BA"],
    ["Ceará", "CE"],
    ["Distrito Federal", "DF"],
    ["Espírito Santo", "ES"],
    ["Goiás", "GO"],
    ["Maranhão", "MA"],
    ["Mato Grosso", "MT"],
    ["Mato Grosso do Sul", "MS"],
    ["Minas Gerais", "MG"],
    ["Pará", "PA"],
    ["Paraíba", "PB"],
    ["Paraná", "PR"],
    ["Pernambuco", "PE"],
    ["Piauí", "PI"],
    ["Rio de Janeiro", "RJ"],
    ["Rio Grande do Norte", "RN"],
    ["Rio Grande do Sul", "RS"],
    ["Rondônia", "RO"],
    ["Roraima", "RR"],
    ["Santa Catarina", "SC"],
    ["São Paulo", "SP"],
    ["Sergipe", "SE"],
    ["Tocantins", "TO"]
  ]
  
  def options_for_states(selected)
    options_for_select(ESTADOS_BRASILEIROS, selected)
  end
  
  def mostrar_meu_nome
    "Ícaro Falcão"
  end
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/telefones_helper.rb
module TelefonesHelper
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/contatos/_form.html.erb
<%= form_for(@contato, html: {class: "elegant-aero"}) do |f| %>
  <h1><%= @contato.model_name.human %></h1>
 <% if @contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contato.errors.count, "erro") %> proibiu esse contato de ser salvo:</h2>

      <ul>
      <% @contato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
    <small class="form-text text-muted">Digite o nome completo.</small>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.fields_for :endereco do |campos_endereco| %>
      Rua:<br> <%= campos_endereco.text_field :rua %><br>
      Cidade:<br> <%= campos_endereco.text_field :cidade %><br>
      Estado:<br> <%= campos_endereco.select :estado, options_for_states(@contato.endereco.estado) %><br>
    <% end %>
  </div>
  <div id="telefones">
    <%= f.fields_for :telefones do |campos_telefones| %>
      <%= render partial: "telefone_fields", locals: { f: campos_telefones}%>
    <% end %>
    <%= f.label :telefones, "<span class='glyphicon glyphicon-phone-alt' aria-hidden='true'></span>".html_safe %>
    <%= link_to_add_association('Adicionar Telefone:', f, :telefones) %><br>
  </div>
  <div class="field">
    <br>
    <%= f.label :tipo_id %>
    <%= f.collection_select(:tipo_id, @opcoes_tipos_para_select, :id, :descricao) %>
    <!-- Quem vai receber essa coleção, aonde vai receber, do quê?, campo que vai ser enviado, campo que será mostrado -->
  </div>
  <div class="field">
    <label for="observacao">Observação:</label>
    <%= f.text_area :observacao %>
  </div>
  <div class="actions">
    <%= f.submit "Enviar", class: "btn btn-success" %>
    <%= link_to t('back'), :back, class: "btn btn-info" %>
  </div>
<% end %>

app/views/contatos/_rodape.html.erb
<h4> Developed By Ícaro Falcão. All Rights Reserved. 2017.</h4>

app/views/contatos/_telefone_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :telefone %>
    <%= f.text_field :telefone %>
    <%= link_to_remove_association('Remover', f) %>
  </div>
</div>

app/views/contatos/edit.html.erb
<%= render 'form' %>

app/views/contatos/index.html.erb
<div class="elegant-aero">
  <script>
    $.notify("<%= notice %>", "success");
  </script>

  <h1><%= "#{t('messages.listing')} #{@contatos.model_name.human(count: @contatos.count)}" %></h1>

  <table class="table table-bordered">
    <thead class="thead-inverse">
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Tipo</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @contatos.each do |contato| %>
        <tr style="background: <%= cycle('white', '#F9FFE4') -%>">
          <td><%= contato.nome %></td>
          <td><%= contato.email %></td>
          <td><%= contato.tipo.descricao %></td>
          <td><%= link_to t('edit'), edit_contato_path(contato), class:"btn btn-warning" %></td>
          <td><%= link_to t('destroy'), contato, class:"btn btn-danger", method: :delete, data: { confirm: t('messages.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
    
  </table>
  <%= paginate(@contatos) %>
  <br>

  <%= link_to t('back'), bemvindo_path, class: "btn btn-info" %>
  <%= link_to t('add'), new_contato_path, class: "btn btn-success" %>

  <%= render partial:"rodape" %>
</div>

app/views/contatos/new.html.erb
<%= render 'form' %>

app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="elegant-aero">
  <p>
    <strong>Nome:</strong>
    <%= @contato.nome %>
  </p>

  <p>
    <strong>E-mail:</strong>
    <%= @contato.email %>
  </p>

  <p>
    <strong>Tipo:</strong>
    <%= @contato.tipo.descricao %>
  </p>

  <p>
    <strong>Observação:</strong>
    <%= @contato.observacao %>
  </p>

  <%= link_to t('edit'), edit_contato_path(@contato) %> |
  <%= link_to t('back'), contatos_path %>
</div>

app/views/home/index.html.erb
<div class="elegant-aero">
  <h1>Seja Bem Vindo</h1>
  <ul class="links-page-inicial">
    <li>  <span class="glyphicon glyphicon-user" aria-hidden="true"></span> - <%= link_to "Contatos", contatos_path, class: "start-link" %> </li>
    <li> <span class="glyphicon glyphicon-tag" aria-hidden="true"></span> - <%= link_to "Tipos", tipos_path, class: "start-link" %> </li>
  </ul>

  <% # REFERENCIAMOS O ARQUIVO A PARTIR DA PASTA views QUANDO ELE NÃO ESTÁ DISPOSTO AUTOMATICAMENTE %>
  <%= render partial:"contatos/rodape" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notebook | The Best App Ever!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tipos/_form.html.erb
<%= form_for(@tipo, html: {class: "elegant-aero"}) do |f| %>
  <h1><%= @tipo.model_name.human %></h1>
  <% if @tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo.errors.count, "erro") %> proibiu esse tipo de ser salvo:</h2>

      <ul>
      <% @tipo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %>
    <%= f.text_field :descricao %>
  </div>
  <div class="actions">
    <%= f.submit "Enviar", class: "btn btn-success"%>
    <%= link_to t('back'), :back, class: "btn btn-info"%>
  </div>
<% end %>

app/views/tipos/edit.html.erb
<%= render 'form' %>

app/views/tipos/index.html.erb
<div class="elegant-aero">
  <script>
    $.notify(" <%= notice %>", "success");
  </script>

  <h1><%= "#{t('messages.listing')} #{@tipos.model_name.human(count: @tipos.count)}" %> </h1>

  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Descrição</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @tipos.each do |tipo| %>
        <tr>
          <td><%= tipo.descricao %></td>
          <td><%= link_to 'Editar', edit_tipo_path(tipo), class: "btn btn-warning" %></td>
          <td><%= link_to 'Apagar', tipo, class: "btn btn-danger", method: :delete, data: { confirm: t('messages.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to t('back'), bemvindo_path, class: "btn btn-info" %>
  <%= link_to t('add'), new_tipo_path, class: "btn btn-success" %>
</div>

app/views/tipos/new.html.erb
<%= render 'form' %>

app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @tipo.descricao %>
</p>

<%= link_to 'Edit', edit_tipo_path(@tipo) %> |
<%= link_to 'Back', tipos_path %>